add index.html and style.css(css)
mswitas/project-front-group-05 pull request #4
Opened 2024-05-13 17:24 UTC by Jakub0821

2024-05-14 14:10 UTC, MagdalenaKusmierczak requested changes

2024-05-14 14:10 UTC, MagdalenaKusmierczak commented on index.html
index html już istnieje w folderze public, plik do usunięcia

2024-05-14 17:12 UTC, MagdalenaKusmierczak commented
ta struktura jest już w projekcie

2024-05-14 17:12 UTC, closed without merging

2024-05-15 17:23 UTC, Jakub0821 commented on index.html
Ok